
#ifndef OPERATIONS_FOR_REQUEST_GEN
#define OPERATIONS_FOR_REQUEST_GEN

#define GET_DECIMAL_FROM_RANGE "GET_DECIMAL_FROM_RANGE"
#define GET_DECIMAL_NEAR_POINT "GET_DECIMAL_NEAR_POINT"
#define RANGE 0
#define NEAR_POINT 1

#define MAX_OPERATION_SIZE 25
#endif
