#ifndef FUNCTION_FOR_GENERATE
#define FUNCTION_FOR_GENERATE

#include <stdio.h>

#include "./OperationForGenerate.h"
#include "../libs/s21_decimal.h"

/// @brief Reads a decimal number from a range generated by C#.
/// @param stream
/// @return 0 - You can continue.
/// @return 1 - Stream ended.
int GetDecimalFromRange(FILE *stream, s21_decimal *result);

/// @brief Requests C# to generate a numbers range.
/// @param number
/// @param step
/// @return Stream of numbers.
/// @attention Requires closing the request or using GetDecimalFromRange until 1
/// is returned.
FILE *GetRequestPeriodic(int number, s21_decimal *step);

/// @brief Requests C# to generate a numbers range.
/// @param start
/// @param end
/// @param step
/// @return Stream of numbers.
/// @attention Requires closing the request or using GetDecimalFromRange until 1
/// is returned.
FILE *GetRequestRange(s21_decimal *start, s21_decimal *end, s21_decimal *step);

/// @brief Requests C# to generate a reverse numbers range.
/// @param start
/// @param end
/// @param step
/// @return Stream of numbers.
/// @attention Requires closing the request or using GetDecimalFromRange until 1
/// is returned.
FILE *GetRequestReverseRange(s21_decimal *start, s21_decimal *end,
                             s21_decimal *step);

/// @brief Close stream.
/// @param stream
void CloseRangeRequest(FILE *stream);
#endif