
#ifndef OPERATIONS_FOR_REQUEST
#define OPERATIONS_FOR_REQUEST

#define SUM_OP "SUM"
#define SUB_OP "SUB"
#define MUL_OP "MUL"
#define DIV_OP "DIV"
#define REMAINDER_OP "MOD"

#define LESS_OP "LESS"
#define MORE_OP "MORE"
#define MORE_OR_EQUAL_OP "MORE_OR_EQUAL"
#define EQUAL_OP "EQUAL"
#define LESS_OR_EQUAL_OP "LESS_OR_EQUAL"
#define NOT_EQUAL_OP "NOT_EQUAL"

#define CONVERT_DECIMAL_TO_INT_OP "D2I"
#define CONVERT_DECIMAL_TO_FLOAT_OP "D2F"
#define CONVERT_INT_TO_DECIMAL_OP "I2D"
#define CONVERT_FLOAT_TO_DECIMAL_OP "F2D"

#define NEGATIVE_OP "NEGATIVE"
#define FLOOR_OP "FLOOR"
#define ROUND_OP "ROUND"
#define TRUNCATE_OP "TRUNCATE"
#endif
